// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoxGame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class BoxSystemGuessEventHandler {
        
        public Box Group;
        
        private BoxGame.GuessEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode49_go = default( UnityEngine.GameObject );
        
        private UnityEngine.MonoBehaviour ActionNode49_component = default( UnityEngine.MonoBehaviour );
        
        private UnityEngine.Rigidbody ActionNode49_Result = default( UnityEngine.Rigidbody );
        
        private float ActionNode61_minX = default( System.Single );
        
        private float FloatNode62 = 0F;
        
        private float ActionNode61_maxX = default( System.Single );
        
        private float ActionNode61_minY = default( System.Single );
        
        private float FloatNode51 = 20F;
        
        private float ActionNode61_maxY = default( System.Single );
        
        private float FloatNode52 = 150F;
        
        private float ActionNode61_minZ = default( System.Single );
        
        private float ActionNode61_maxZ = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode61_Result = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode47_direction = default( UnityEngine.Vector3 );
        
        private UnityEngine.Rigidbody ActionNode47_rigidBody = default( UnityEngine.Rigidbody );
        
        private BoxGame.PushBox ActionNode47 = new BoxGame.PushBox();
        
        public BoxGame.GuessEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode49_go = Group.gameObject;
            // ActionNode
            // Visit uFrame.Actions.UnityLibrary.GetRigidbody
            ActionNode49_Result = uFrame.Actions.UnityLibrary.GetRigidbody(ActionNode49_go, ActionNode49_component);
            ActionNode61_minX = FloatNode62;
            ActionNode61_maxX = FloatNode62;
            ActionNode61_minY = FloatNode51;
            ActionNode61_maxY = FloatNode52;
            ActionNode61_minZ = FloatNode62;
            ActionNode61_maxZ = FloatNode62;
            // ActionNode
            // Visit uFrame.Actions.CreateRandoms.RandomVector3
            ActionNode61_Result = uFrame.Actions.CreateRandoms.RandomVector3(ActionNode61_minX, ActionNode61_maxX, ActionNode61_minY, ActionNode61_maxY, ActionNode61_minZ, ActionNode61_maxZ);
            ActionNode47_direction = ActionNode61_Result;
            ActionNode47_rigidBody = ActionNode49_Result;
            // ActionNode
            // Visit BoxGame.PushBox
            ActionNode47.direction = ActionNode47_direction;
            ActionNode47.rigidBody = ActionNode47_rigidBody;
            ActionNode47.System = System;
            ActionNode47.Execute();
        }
    }
}
