// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoxGame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using uFrame.Kernel;
    
    
    public class GuessedHigherHandler {
        
        public GuessLabel Group;
        
        private BoxGame.HigherEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private BoxGame.GuessEvent PublishEventNode32_Result = default( BoxGame.GuessEvent );
        
        public BoxGame.HigherEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // PublishEventNode
            var PublishEventNode32_Event = new GuessEvent();
            PublishEventNode32_Event.min = Group.guess;
            PublishEventNode32_Event.max = Group.max;
            System.Publish(PublishEventNode32_Event);
            PublishEventNode32_Event = PublishEventNode32_Result;
        }
    }
}
