// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BoxGame {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.uFrameIdentifier("a8bbaa28-7df6-415d-a5c2-95b2d7a4f977")]
    public partial class BoxSystem : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<GuessLabel> _GuessLabelManager;
        
        private IEcsComponentManagerOf<LowerButton> _LowerButtonManager;
        
        private IEcsComponentManagerOf<HigherButton> _HigherButtonManager;
        
        private IEcsComponentManagerOf<Box> _BoxManager;
        
        private BoxSystemGameReadyEventHandler BoxSystemGameReadyEventHandlerInstance = new BoxSystemGameReadyEventHandler();
        
        private BoxGameReadyHandler BoxGameReadyHandlerInstance = new BoxGameReadyHandler();
        
        private BoxSystemGuessEventHandler BoxSystemGuessEventHandlerInstance = new BoxSystemGuessEventHandler();
        
        private BoxnamePropertyChanged BoxnamePropertyChangedInstance = new BoxnamePropertyChanged();
        
        public IEcsComponentManagerOf<GuessLabel> GuessLabelManager {
            get {
                return _GuessLabelManager;
            }
            set {
                _GuessLabelManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LowerButton> LowerButtonManager {
            get {
                return _LowerButtonManager;
            }
            set {
                _LowerButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<HigherButton> HigherButtonManager {
            get {
                return _HigherButtonManager;
            }
            set {
                _HigherButtonManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Box> BoxManager {
            get {
                return _BoxManager;
            }
            set {
                _BoxManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            GuessLabelManager = ComponentSystem.RegisterComponent<GuessLabel>();
            LowerButtonManager = ComponentSystem.RegisterComponent<LowerButton>();
            HigherButtonManager = ComponentSystem.RegisterComponent<HigherButton>();
            BoxManager = ComponentSystem.RegisterComponent<Box>();
            this.OnEvent<uFrame.Kernel.GameReadyEvent>().Subscribe(_=>{ BoxSystemGameReadyEventFilter(_); }).DisposeWith(this);
            this.OnEvent<uFrame.Kernel.GameReadyEvent>().Subscribe(_=>{ BoxGameReadyFilter(_); }).DisposeWith(this);
            this.OnEvent<BoxGame.GuessEvent>().Subscribe(_=>{ BoxSystemGuessEventFilter(_); }).DisposeWith(this);
            this.PropertyChanged<Box,String>(Group=>Group.nameObservable, BoxnamePropertyChangedFilter);
        }
        
        protected void BoxSystemGameReadyEventHandler(uFrame.Kernel.GameReadyEvent data) {
            var handler = BoxSystemGameReadyEventHandlerInstance;;
            handler.System = this;
            handler.Event = data;
            handler.Execute();
        }
        
        protected void BoxSystemGameReadyEventFilter(uFrame.Kernel.GameReadyEvent data) {
            this.BoxSystemGameReadyEventHandler(data);
        }
        
        protected void BoxGameReadyHandler(uFrame.Kernel.GameReadyEvent data, Box group) {
            var handler = BoxGameReadyHandlerInstance;;
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void BoxGameReadyFilter(uFrame.Kernel.GameReadyEvent data) {
            var BoxItems = BoxManager.Components;
            for (var BoxIndex = 0
            ; BoxIndex < BoxItems.Count; BoxIndex++
            ) {
                this.BoxGameReadyHandler(data, BoxItems[BoxIndex]);
            }
        }
        
        protected void BoxSystemGuessEventHandler(BoxGame.GuessEvent data, Box group) {
            var handler = BoxSystemGuessEventHandlerInstance;;
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void BoxSystemGuessEventFilter(BoxGame.GuessEvent data) {
            var BoxItems = BoxManager.Components;
            for (var BoxIndex = 0
            ; BoxIndex < BoxItems.Count; BoxIndex++
            ) {
                this.BoxSystemGuessEventHandler(data, BoxItems[BoxIndex]);
            }
        }
        
        protected void BoxnamePropertyChanged(Box data, Box group, String value) {
            var handler = BoxnamePropertyChangedInstance;;
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void BoxnamePropertyChangedFilter(Box data, String value) {
            var GroupBox = BoxManager[data.EntityId];
            if (GroupBox == null) {
                return;
            }
            this.BoxnamePropertyChanged(data, GroupBox, value);
        }
    }
}
